version: '3.8'

volumes:
  prometheus_data:
  grafana_data:

services:  
  # prometheus:
  #   image: prom/prometheus:latest
  #   volumes:
  #     - ./prometheus:/etc/prometheus/
  #     - prometheus_data:/prometheus
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #     - "--storage.tsdb.path=/prometheus"
  #     - "--web.listen-address=0.0.0.0:9090"
  #     - "--web.route-prefix=/"
  #     - "--web.external-url=http://127.0.0.1:9090/prometheus"
  #     - "--web.console.libraries=/usr/share/prometheus/console_libraries"
  #     - "--web.console.templates=/usr/share/prometheus/consoles"
  #     - "--web.enable-lifecycle"
  #   restart: always
  #   ports:
  #     - 9090:9090
  #   networks:
  #     - local
    # network_mode: "host"

  node_exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - local

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    networks:
      - local
    # network_mode: "host"
 
  brokers:
    image: amirhosseinrazlighi/server_app:latest
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - zookeepers
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - local
    environment:
      - ZOOKEEPER=sad-zookeepers-1

  zookeepers:
    image: amirhosseinrazlighi/zookeeper_app:latest
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 20s
      timeout: 10s
      retries: 3
    networks:
      - local


  clients:
    image: amirhosseinrazlighi/client_app:latest
    deploy:
      mode: replicated
      replicas: 1
    # entrypoint: sleep 10000
    depends_on:
      brokers:
        condition: service_healthy
      zookeepers:
        condition: service_healthy
    environment:
      - BROKER=sad-brokers-1
      - ZOOKEEPER=sad-zookeepers-1
    networks:
      - local


networks:
  local:
    driver: bridge