version: '3.8'

volumes:
  prometheus_data:
  grafana_data:
services:
  # prometheus:
  #   image: prometheus:2.34.0
  #   volumes:
  #     - ./prometheus:/etc/prometheus/
  #     - prometheus_data:/prometheus
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #     - "--storage.tsdb.path=/prometheus"
  #     - "--web.listen-address=0.0.0.0:9090"
  #     - "--web.route-prefix=/"
  #     - "--web.external-url=http://127.0.0.1:9090/prometheus"
  #     - "--web.console.libraries=/usr/share/prometheus/console_libraries"
  #     - "--web.console.templates=/usr/share/prometheus/consoles"
  #     - "--web.enable-lifecycle"
  #   restart: always
  #   network_mode: "host"

  brokers:
    image: server_app:latest
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - zookeepers
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - local
    environment:
      - ZOOKEEPER=sad-zookeepers-1

  zookeepers:
    image: zookeeper_app:latest
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 20s
      timeout: 10s
      retries: 3
    networks:
      - local


  clients:
    image: client_app:latest
    deploy:
      mode: replicated
      replicas: 1
    # entrypoint: sleep 10000
    depends_on:
      brokers:
        condition: service_healthy
      zookeepers:
        condition: service_healthy
    environment:
      - BROKER=sad-brokers-1
      - ZOOKEEPER=sad-zookeepers-1
    networks:
      - local


networks:
  local:
    driver: bridge