# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#            - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
        - "rules/first_rules.yml"
        # - "rules/bb-alert.rules"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  # Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    basic_auth:
      username: 'user1'
      password: 'password'

  # - job_name: 'blackbox' # To get metrics about the exporter itself.
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets:
  #       - localhost:9115

  # - job_name: "blackbox-http" # To get metrics about the exporter’s targets
  #   metrics_path: /probe
  #   params:
  #     module: 
  #       - http_2xx
  #   file_sd_configs:
  #     - files:
  #       - "files_sd/bb-http.yml"
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: localhost:9115

  # - job_name: blackbox-icmp # To get metrics about the exporter’s targets
  #   metrics_path: /probe
  #   params:
  #     module: [ping]
  #   file_sd_configs:
  #     - files:
  #       - "files_sd/bb-icmp.yml"
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: localhost:9115

  # - job_name: 'node-exporter' 
  #   static_configs: 
  #     - targets: 
  #         - '192.168.1.11:9100'
  #         - '192.168.0.12:9100'
  #         - '192.168.0.11:9100'
  #         - '192.168.0.14:9100'
  #         - 'localhost:9100'
  #         - '192.168.0.10:9100'
  #         - '185.235.40.21:9100'

  # - job_name: "rest-app-exporter"
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: 
  #         - '192.168.0.11:18080'
