name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client
      
      - name: Write SSH private key to id_rsa
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ~/.ssh/known_hosts

      - name: Add server to known hosts
        run: |
          ssh-keyscan 185.97.117.121 >> $HOME/.ssh/known_hosts

      - name: Install Docker and Docker Compose on server
        run: |
          ssh -i $HOME/.ssh/id_rsa ubuntu@185.97.117.121 << EOF
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          EOF

      - name: Deploy Application
        run: |
          ssh -i $HOME/.ssh/id_rsa ubuntu@185.97.117.121 "echo 'Deployment successful!'"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Pull and run Docker images
        run: |
          ssh -i $HOME/.ssh/id_rsa ubuntu@185.97.117.121 << EOF
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/server_app:latest
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/zookeeper_app:latest
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/client_app:latest
          docker-compose -p "sad" up
          EOF