name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build client_app Docker image
      run: docker build -t client_app:latest client/

    - name: Build server_app Docker image
      run: docker build -t server_app:latest server/
      
    - name: Start server_app container
      run: docker run -d --name server_app server_app:latest

    - name: Test server unit tests
      run: |
        docker exec server_app sh -c "cd tests/ && python3 -m unittest test_api && python3 -m unittest test_push"

    - name: Stop and remove server_app container
      run: |
        docker stop server_app
        docker rm server_app

    - name: Test Docker Compose
      run: |
        docker-compose -f ./docker-compose.yml -p "sad" up -d
        sleep 35
        docker-compose -f ./docker-compose.yml -p "sad" down
